spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.foam.photo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml